export enum HTTP_METHOD {
	GET = 'GET',
	POST = 'POST',
	PUT = 'PUT',
	PATCH = 'PATCH',
	DELETE = 'DELETE',
	HEAD = 'HEAD',
	OPTIONS = 'OPTIONS',
	CONNECT = 'CONNECT',
	TRACE = 'TRACE',
}

export enum REQUEST_CREDENTIALS {
	INCLUDE = 'include',
	OMIT = 'omit',
	SAME_ORIGIN = 'same-origin',
}

export enum STATUS {
	OK = '200',
	CREATED = '201',
	ACCEPTED = '202',
	NO_CONTENT = '204',
	BAD_REQUEST = '400',
	UNAUTHORIZED = '401',
	PAYMENT_REQUIRED = '402',
	FORBIDDEN = '403',
	NOT_FOUND = '404',
	METHOD_NOT_ALLOWED = '405',
	NOT_ACCEPTABLE = '406',
	REQUEST_TIMEOUT = '408',
	CONFLICT = '409',
	GONE = '410',
	UNPROCESSABLE_ENTITY = '422',
	TOO_MANY_REQUESTS = '429',
	INTERNAL_SERVER_ERROR = '500',
	NOT_IMPLEMENTED = '501',
	BAD_GATEWAY = '502',
	SERVICE_UNAVAILABLE = '503',
	GATEWAY_TIMEOUT = '504',
}

export enum HEADER {
	ACCEPT = 'Accept',
	ACCEPT_ENCODING = 'Accept-Encoding',
	ACCEPT_LANGUAGE = 'Accept-Language',
	AUTH = 'Authorization',
	CACHE_CONTROL = 'Cache-Control',
	CONNECTION = 'Connection',
	CONTENT_ENCODING = 'Content-Encoding',
	CONTENT_LENGTH = 'Content-Length',
	CONTENT_TYPE = 'Content-Type',
	COOKIE = 'Cookie',
	DATE = 'Date',
	ETAG = 'ETag',
	HOST = 'Host',
	IF_MODIFIED_SINCE = 'If-Modified-Since',
	IF_NONE_MATCH = 'If-None-Match',
	LAST_MODIFIED = 'Last-Modified',
	LOCATION = 'Location',
	ORIGIN = 'Origin',
	REFERER = 'Referer',
	SET_COOKIE = 'Set-Cookie',
	USER_AGENT = 'User-Agent',
	X_FORWARDED_FOR = 'X-Forwarded-For',
	X_FORWARDED_HOST = 'X-Forwarded-Host',
	X_FORWARDED_PROTO = 'X-Forwarded-Proto',
	X_REQUESTED_WITH = 'X-Requested-With',
}

export enum CONTENT_TYPE {
	APPLICATION_FORM_URLENCODED = 'application/x-www-form-urlencoded',
	APPLICATION_JAVASCRIPT = 'application/javascript',
	APPLICATION_JSON = 'application/json',
	APPLICATION_OCTET_STREAM = 'application/octet-stream',
	APPLICATION_PDF = 'application/pdf',
	APPLICATION_XML = 'application/xml',
	APPLICATION_ZIP = 'application/zip',
	IMAGE_GIF = 'image/gif',
	IMAGE_JPEG = 'image/jpeg',
	IMAGE_PNG = 'image/png',
	IMAGE_SVG = 'image/svg+xml',
	IMAGE_WEBP = 'image/webp',
	MULTIPART_FORM_DATA = 'multipart/form-data',
	TEXT_CSS = 'text/css',
	TEXT_HTML = 'text/html',
	TEXT_JAVASCRIPT = 'text/javascript',
	TEXT_PLAIN = 'text/plain',
}
